### ISSUE TITLE
Refuse issue

### ISSUE THREAD

**Issue by Dr-Camper** [wimpysworld/desktopify#25]
If I run the command "git clone https://github.com/wimpysworld/desktopify.git" there comes the error
"Cloning into 'desktopify'...
fatal: unable to access 'https:// ... ': Failed to connect to github.com port 443: Connection refused"
I'm connected with LAN
I'm from Germany, but why is Github refusing to connect?
Is it my region?

**Comment by orochikun** [comment]
There seems to be an error with this project page, since I  attempted to clog from rpi and mac , triple flash , same problem

**Comment by orochikun** [comment]
Nevermind,  I had a typo

**Comment by Dr-Camper** [comment]
when will the error be fixed

**Comment by orochikun** [comment]
Hey , quick suggestion , try to clone other repo from another dev ( using GitHub of course) if that fails then the issue is with GitHub or your connection from Germany to this server, but if that works then .. There might be a typo on your part, trust me I validated 3+times and thought I had it right,

Hope this helps

**Comment by Dr-Camper** [comment]
On another repo's there comes the same error. I guess my internet provider don't let me access or the router settings are wrong. Thanks anyway for the help.

**Comment by Dr-Camper** [comment]
Now i solved the problem. There was an issue in the router settings. Now everthing is working fine.
